import ChernoffFace from "./ChernoffFace/ChernoffFace";

export const globalState = {
  facesCorruption: [
    <ChernoffFace
      chernoffAttributes={{
        body: "neutral",
        eyebrows: "low",
        mouth: "neutral",
        nose: "low",
        neck: "low",
      }}
      externalClass={"trialFace"}
      country="trialFace"
    />,
    <ChernoffFace
      chernoffAttributes={{
        body: "neutral",
        eyebrows: "neutral",
        mouth: "neutral",
        nose: "low",
        neck: "low",
      }}
      externalClass={"trialFace"}
      country="trialFace"
    />,
    <ChernoffFace
      chernoffAttributes={{
        body: "neutral",
        eyebrows: "high",
        mouth: "neutral",
        nose: "low",
        neck: "low",
      }}
      externalClass={"trialFace"}
      country="trialFace"
    />,
  ],

  facesDrugs: [
    <ChernoffFace
      chernoffAttributes={{
        body: "neutral",
        eyebrows: "neutral",
        mouth: "neutral",
        nose: "low",
        neck: "low",
      }}
      externalClass={"trialFace"}
      country="trialFace"
    />,
    <ChernoffFace
      chernoffAttributes={{
        body: "neutral",
        eyebrows: "neutral",
        mouth: "neutral",
        nose: "high",
        neck: "low",
      }}
      externalClass={"trialFace"}
      country="trialFace"
    />,
  ],
  facesHappiness: [
    <ChernoffFace
      chernoffAttributes={{
        body: "neutral",
        eyebrows: "neutral",
        mouth: "low",
        nose: "low",
        neck: "low",
      }}
      externalClass={"trialFace"}
      country="trialFace"
    />,
    <ChernoffFace
      chernoffAttributes={{
        body: "neutral",
        eyebrows: "neutral",
        mouth: "neutral",
        nose: "low",
        neck: "low",
      }}
      externalClass={"trialFace"}
      country="trialFace"
    />,
    <ChernoffFace
      chernoffAttributes={{
        body: "neutral",
        eyebrows: "neutral",
        mouth: "high",
        nose: "low",
        neck: "low",
      }}
      externalClass={"trialFace"}
      country="trialFace"
    />,
  ],
  facesObesity: [
    <ChernoffFace
      chernoffAttributes={{
        body: "neutral",
        eyebrows: "neutral",
        mouth: "neutral",
        nose: "low",
        neck: "low",
      }}
      externalClass={"trialFace"}
      country="trialFace"
    />,
    <ChernoffFace
      chernoffAttributes={{
        body: "neutral",
        eyebrows: "neutral",
        mouth: "neutral",
        nose: "low",
        neck: "high",
      }}
      externalClass={"trialFace"}
      country="trialFace"
    />,
  ],
  facesSkin: [
    <ChernoffFace
      chernoffAttributes={{
        body: "low",
        eyebrows: "neutral",
        mouth: "neutral",
        nose: "low",
        neck: "low",
      }}
      externalClass={"trialFace"}
      country="trialFace"
    />,
    <ChernoffFace
      chernoffAttributes={{
        body: "neutral",
        eyebrows: "neutral",
        mouth: "neutral",
        nose: "low",
        neck: "low",
      }}
      externalClass={"trialFace"}
      country="trialFace"
    />,
    <ChernoffFace
      chernoffAttributes={{
        body: "high",
        eyebrows: "neutral",
        mouth: "neutral",
        nose: "low",
        neck: "low",
      }}
      externalClass={"trialFace"}
      country="trialFace"
    />,
  ],
};

export const dataset = {
  Austria: {
    countryName: "Austria",
    Code: "AUT",
    Flag: "\ud83c\udde6\ud83c\uddf9",
    CorruptionIndex: 76,
    UVIndex: 1888,
    ObesityIndex: 21.9,
    HappinessIndex: 7.246,
    DrugDeaths: 140.0,
    CorruptionIndex_Parsed: "low",
    UVIndex_Parsed: "neutral",
    ObesityIndex_Parsed: "low",
    HappinessIndex_Parsed: "high",
    DrugDeaths_Parsed: "low",
  },
  Belgium: {
    countryName: "Belgium",
    Code: "BEL",
    Flag: "\ud83c\udde7\ud83c\uddea",
    CorruptionIndex: 75,
    UVIndex: 1645,
    ObesityIndex: 24.5,
    HappinessIndex: 6.923,
    DrugDeaths: 224.0,
    CorruptionIndex_Parsed: "neutral",
    UVIndex_Parsed: "low",
    ObesityIndex_Parsed: "low",
    HappinessIndex_Parsed: "neutral",
    DrugDeaths_Parsed: "high",
  },
  Bulgaria: {
    countryName: "Bulgaria",
    Code: "BGR",
    Flag: "\ud83c\udde7\ud83c\uddec",
    CorruptionIndex: 42,
    UVIndex: 2331,
    ObesityIndex: 27.4,
    HappinessIndex: 5.011,
    DrugDeaths: 69.0,
    CorruptionIndex_Parsed: "high",
    UVIndex_Parsed: "high",
    ObesityIndex_Parsed: "high",
    HappinessIndex_Parsed: "low",
    DrugDeaths_Parsed: "low",
  },
  Croatia: {
    countryName: "Croatia",
    Code: "HRV",
    Flag: "\ud83c\udded\ud83c\uddf7",
    CorruptionIndex: 48,
    UVIndex: 1976,
    ObesityIndex: 27.1,
    HappinessIndex: 5.4318,
    DrugDeaths: 70.0,
    CorruptionIndex_Parsed: "high",
    UVIndex_Parsed: "neutral",
    ObesityIndex_Parsed: "high",
    HappinessIndex_Parsed: "low",
    DrugDeaths_Parsed: "low",
  },
  Cyprus: {
    countryName: "Cyprus",
    Code: "CYP",
    Flag: "\ud83c\udde8\ud83c\uddfe",
    CorruptionIndex: 59,
    UVIndex: 3439,
    ObesityIndex: 22.6,
    HappinessIndex: 6.0458,
    DrugDeaths: 17.0,
    CorruptionIndex_Parsed: "neutral",
    UVIndex_Parsed: "high",
    ObesityIndex_Parsed: "low",
    HappinessIndex_Parsed: "neutral",
    DrugDeaths_Parsed: "low",
  },
  Czechia: {
    countryName: "Czechia",
    Code: "CZE",
    Flag: "\ud83c\udde8\ud83c\uddff",
    CorruptionIndex: 59,
    UVIndex: 1707,
    ObesityIndex: 28.5,
    HappinessIndex: 6.8521,
    DrugDeaths: 136.0,
    CorruptionIndex_Parsed: "neutral",
    UVIndex_Parsed: "neutral",
    ObesityIndex_Parsed: "high",
    HappinessIndex_Parsed: "neutral",
    DrugDeaths_Parsed: "low",
  },
  Denmark: {
    countryName: "Denmark",
    Code: "DNK",
    Flag: "\ud83c\udde9\ud83c\uddf0",
    CorruptionIndex: 88,
    UVIndex: 1691,
    ObesityIndex: 21.3,
    HappinessIndex: 7.6001,
    DrugDeaths: 198.0,
    CorruptionIndex_Parsed: "low",
    UVIndex_Parsed: "neutral",
    ObesityIndex_Parsed: "low",
    HappinessIndex_Parsed: "high",
    DrugDeaths_Parsed: "low",
  },
  Estonia: {
    countryName: "Estonia",
    Code: "EST",
    Flag: "\ud83c\uddea\ud83c\uddea",
    CorruptionIndex: 73,
    UVIndex: 1781,
    ObesityIndex: 23.8,
    HappinessIndex: 5.8935,
    DrugDeaths: 128.0,
    CorruptionIndex_Parsed: "neutral",
    UVIndex_Parsed: "neutral",
    ObesityIndex_Parsed: "low",
    HappinessIndex_Parsed: "low",
    DrugDeaths_Parsed: "low",
  },
  Finland: {
    countryName: "Finland",
    Code: "FIN",
    Flag: "\ud83c\uddeb\ud83c\uddee",
    CorruptionIndex: 85,
    UVIndex: 1494,
    ObesityIndex: 24.9,
    HappinessIndex: 7.7689,
    DrugDeaths: 291.0,
    CorruptionIndex_Parsed: "low",
    UVIndex_Parsed: "low",
    ObesityIndex_Parsed: "high",
    HappinessIndex_Parsed: "high",
    DrugDeaths_Parsed: "high",
  },
  France: {
    countryName: "France",
    Code: "FRA",
    Flag: "\ud83c\uddeb\ud83c\uddf7",
    CorruptionIndex: 72,
    UVIndex: 1907,
    ObesityIndex: 23.2,
    HappinessIndex: 6.5921,
    DrugDeaths: 1839.0,
    CorruptionIndex_Parsed: "neutral",
    UVIndex_Parsed: "neutral",
    ObesityIndex_Parsed: "low",
    HappinessIndex_Parsed: "neutral",
    DrugDeaths_Parsed: "high",
  },
  Germany: {
    countryName: "Germany",
    Code: "DEU",
    Flag: "\ud83c\udde9\ud83c\uddea",
    CorruptionIndex: 80,
    UVIndex: 1812,
    ObesityIndex: 25.7,
    HappinessIndex: 6.985,
    DrugDeaths: 1678.0,
    CorruptionIndex_Parsed: "low",
    UVIndex_Parsed: "neutral",
    ObesityIndex_Parsed: "high",
    HappinessIndex_Parsed: "neutral",
    DrugDeaths_Parsed: "high",
  },
  Greece: {
    countryName: "Greece",
    Code: "GRC",
    Flag: "\ud83c\uddec\ud83c\uddf7",
    CorruptionIndex: 45,
    UVIndex: 2753,
    ObesityIndex: 27.4,
    HappinessIndex: 5.2867,
    DrugDeaths: 186.0,
    CorruptionIndex_Parsed: "high",
    UVIndex_Parsed: "high",
    ObesityIndex_Parsed: "high",
    HappinessIndex_Parsed: "low",
    DrugDeaths_Parsed: "low",
  },
  Hungary: {
    countryName: "Hungary",
    Code: "HUN",
    Flag: "\ud83c\udded\ud83c\uddfa",
    CorruptionIndex: 46,
    UVIndex: 1932,
    ObesityIndex: 28.6,
    HappinessIndex: 5.7583,
    DrugDeaths: 63.0,
    CorruptionIndex_Parsed: "high",
    UVIndex_Parsed: "neutral",
    ObesityIndex_Parsed: "high",
    HappinessIndex_Parsed: "low",
    DrugDeaths_Parsed: "low",
  },
  Ireland: {
    countryName: "Ireland",
    Code: "IRL",
    Flag: "\ud83c\uddee\ud83c\uddea",
    CorruptionIndex: 73,
    UVIndex: 1509,
    ObesityIndex: 26.9,
    HappinessIndex: 7.0211,
    DrugDeaths: 200.0,
    CorruptionIndex_Parsed: "neutral",
    UVIndex_Parsed: "low",
    ObesityIndex_Parsed: "high",
    HappinessIndex_Parsed: "high",
    DrugDeaths_Parsed: "low",
  },
  Italy: {
    countryName: "Italy",
    Code: "ITA",
    Flag: "\ud83c\uddee\ud83c\uddf9",
    CorruptionIndex: 52,
    UVIndex: 2444,
    ObesityIndex: 22.9,
    HappinessIndex: 6.2234,
    DrugDeaths: 563.0,
    CorruptionIndex_Parsed: "high",
    UVIndex_Parsed: "high",
    ObesityIndex_Parsed: "low",
    HappinessIndex_Parsed: "neutral",
    DrugDeaths_Parsed: "high",
  },
  Latvia: {
    countryName: "Latvia",
    Code: "LVA",
    Flag: "\ud83c\uddf1\ud83c\uddfb",
    CorruptionIndex: 58,
    UVIndex: 1671,
    ObesityIndex: 25.7,
    HappinessIndex: 5.9397,
    DrugDeaths: 51.0,
    CorruptionIndex_Parsed: "neutral",
    UVIndex_Parsed: "low",
    ObesityIndex_Parsed: "high",
    HappinessIndex_Parsed: "low",
    DrugDeaths_Parsed: "low",
  },
  Lithuania: {
    countryName: "Lithuania",
    Code: "LTU",
    Flag: "\ud83c\uddf1\ud83c\uddf9",
    CorruptionIndex: 59,
    UVIndex: 1801,
    ObesityIndex: 28.4,
    HappinessIndex: 6.149,
    DrugDeaths: 169.0,
    CorruptionIndex_Parsed: "neutral",
    UVIndex_Parsed: "neutral",
    ObesityIndex_Parsed: "high",
    HappinessIndex_Parsed: "neutral",
    DrugDeaths_Parsed: "low",
  },
  Luxembourg: {
    countryName: "Luxembourg",
    Code: "LUX",
    Flag: "\ud83c\uddf1\ud83c\uddfa",
    CorruptionIndex: 81,
    UVIndex: 1687,
    ObesityIndex: 24.2,
    HappinessIndex: 7.0903,
    DrugDeaths: 15.0,
    CorruptionIndex_Parsed: "low",
    UVIndex_Parsed: "low",
    ObesityIndex_Parsed: "low",
    HappinessIndex_Parsed: "high",
    DrugDeaths_Parsed: "low",
  },
  Malta: {
    countryName: "Malta",
    Code: "MLT",
    Flag: "\ud83c\uddf2\ud83c\uddf9",
    CorruptionIndex: 54,
    UVIndex: 3091,
    ObesityIndex: 31.0,
    HappinessIndex: 6.7256,
    DrugDeaths: 9.0,
    CorruptionIndex_Parsed: "neutral",
    UVIndex_Parsed: "high",
    ObesityIndex_Parsed: "high",
    HappinessIndex_Parsed: "neutral",
    DrugDeaths_Parsed: "low",
  },
  Netherlands: {
    countryName: "Netherlands",
    Code: "NLD",
    Flag: "\ud83c\uddf3\ud83c\uddf1",
    CorruptionIndex: 82,
    UVIndex: 1662,
    ObesityIndex: 23.1,
    HappinessIndex: 7.4876,
    DrugDeaths: 176.0,
    CorruptionIndex_Parsed: "low",
    UVIndex_Parsed: "low",
    ObesityIndex_Parsed: "low",
    HappinessIndex_Parsed: "high",
    DrugDeaths_Parsed: "low",
  },
  Poland: {
    countryName: "Poland",
    Code: "POL",
    Flag: "\ud83c\uddf5\ud83c\uddf1",
    CorruptionIndex: 60,
    UVIndex: 1749,
    ObesityIndex: 25.6,
    HappinessIndex: 6.1817,
    DrugDeaths: 211.0,
    CorruptionIndex_Parsed: "neutral",
    UVIndex_Parsed: "neutral",
    ObesityIndex_Parsed: "high",
    HappinessIndex_Parsed: "neutral",
    DrugDeaths_Parsed: "low",
  },
  Portugal: {
    countryName: "Portugal",
    Code: "PRT",
    Flag: "\ud83c\uddf5\ud83c\uddf9",
    CorruptionIndex: 64,
    UVIndex: 2585,
    ObesityIndex: 23.2,
    HappinessIndex: 5.6925,
    DrugDeaths: 51.0,
    CorruptionIndex_Parsed: "neutral",
    UVIndex_Parsed: "high",
    ObesityIndex_Parsed: "low",
    HappinessIndex_Parsed: "low",
    DrugDeaths_Parsed: "low",
  },
  Romania: {
    countryName: "Romania",
    Code: "ROU",
    Flag: "\ud83c\uddf7\ud83c\uddf4",
    CorruptionIndex: 47,
    UVIndex: 2071,
    ObesityIndex: 24.5,
    HappinessIndex: 6.0697,
    DrugDeaths: 149.0,
    CorruptionIndex_Parsed: "high",
    UVIndex_Parsed: "neutral",
    ObesityIndex_Parsed: "low",
    HappinessIndex_Parsed: "neutral",
    DrugDeaths_Parsed: "low",
  },
  Slovakia: {
    countryName: "Slovakia",
    Code: "SVK",
    Flag: "\ud83c\uddf8\ud83c\uddf0",
    CorruptionIndex: 50,
    UVIndex: 1795,
    ObesityIndex: 22.4,
    HappinessIndex: 6.1976,
    DrugDeaths: 18.0,
    CorruptionIndex_Parsed: "high",
    UVIndex_Parsed: "neutral",
    ObesityIndex_Parsed: "low",
    HappinessIndex_Parsed: "neutral",
    DrugDeaths_Parsed: "low",
  },
  Slovenia: {
    countryName: "Slovenia",
    Code: "SVN",
    Flag: "\ud83c\uddf8\ud83c\uddee",
    CorruptionIndex: 60,
    UVIndex: 2256,
    ObesityIndex: 22.5,
    HappinessIndex: 6.1177,
    DrugDeaths: 28.0,
    CorruptionIndex_Parsed: "neutral",
    UVIndex_Parsed: "neutral",
    ObesityIndex_Parsed: "low",
    HappinessIndex_Parsed: "neutral",
    DrugDeaths_Parsed: "low",
  },
  Spain: {
    countryName: "Spain",
    Code: "ESP",
    Flag: "\ud83c\uddea\ud83c\uddf8",
    CorruptionIndex: 58,
    UVIndex: 2705,
    ObesityIndex: 27.1,
    HappinessIndex: 6.3541,
    DrugDeaths: 728.0,
    CorruptionIndex_Parsed: "neutral",
    UVIndex_Parsed: "high",
    ObesityIndex_Parsed: "high",
    HappinessIndex_Parsed: "neutral",
    DrugDeaths_Parsed: "high",
  },
  Sweden: {
    countryName: "Sweden",
    Code: "SWE",
    Flag: "\ud83c\uddf8\ud83c\uddea",
    CorruptionIndex: 85,
    UVIndex: 1587,
    ObesityIndex: 22.1,
    HappinessIndex: 7.3433,
    DrugDeaths: 485.0,
    CorruptionIndex_Parsed: "low",
    UVIndex_Parsed: "low",
    ObesityIndex_Parsed: "low",
    HappinessIndex_Parsed: "high",
    DrugDeaths_Parsed: "high",
  },
};
